name: 'Build and Publish Base Images.'

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  docker:
    strategy:
      matrix:
        target: [builder, runner]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        id: meta
        name: Setup image tags and labels.
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.target }}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
      -
        id: push
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./infra
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ matrix.target }}
      -
        name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.target }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
